baseURL: "https://braderz.dev/"
languageCode: en-us
title: braderz
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 10
        - name: Search
          url: search/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5    

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  defaultTheme: dark
  description: "You have come accross my website where you might find some ponderings and ramblings of an SRE"
  author: BradErz
  homeInfoParams:
    Title: "Welcome to my ramblings 👋"
    Content: >
      You have come accross my website where you might find some ponderings and ramblings of an SRE

  socialIcons:
  - name: github
    url: "https://github.com/BradErz"
  - name: Twitter
    url: "https://twitter.com/BradErzwh"

  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowReadingTime: true

  # for search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
