---
name: lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            *.md
            !test/*.md
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - run:
          pip install yamllint
      - run: yamllint -c .yamllint.yaml .
